import pytest


@pytest.fixture
def mock_centurion_weather_response():
    return {
        "location": {
            "name": "Centurion",
            "region": "Gauteng",
            "country": "South Africa",
            "lat": -25.87,
            "lon": 28.17,
            "tz_id": "Africa/Johannesburg",
            "localtime_epoch": 1668346753,
            "localtime": "2022-11-13 15:39"
        },
        "current": {
            "last_updated_epoch": 1668346200,
            "last_updated": "2022-11-13 15:30",
            "temp_c": 22.0,
            "temp_f": 71.6,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 130,
            "wind_dir": "SE",
            "pressure_mb": 1017.0,
            "pressure_in": 30.03,
            "precip_mm": 0.6,
            "precip_in": 0.02,
            "humidity": 69,
            "cloud": 0,
            "feelslike_c": 24.6,
            "feelslike_f": 76.2,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "uv": 5.0,
            "gust_mph": 9.6,
            "gust_kph": 15.5
        },
        "forecast": {
            "forecastday": [
                {
                    "date": "2022-11-13",
                    "date_epoch": 1668297600,
                    "day": {
                        "maxtemp_c": 23.3,
                        "maxtemp_f": 73.9,
                        "mintemp_c": 16.1,
                        "mintemp_f": 61.0,
                        "avgtemp_c": 19.3,
                        "avgtemp_f": 66.7,
                        "maxwind_mph": 10.3,
                        "maxwind_kph": 16.6,
                        "totalprecip_mm": 25.1,
                        "totalprecip_in": 0.99,
                        "totalsnow_cm": 0.0,
                        "avgvis_km": 9.2,
                        "avgvis_miles": 5.0,
                        "avghumidity": 78.0,
                        "daily_will_it_rain": 1,
                        "daily_chance_of_rain": 98,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Heavy rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/308.png",
                            "code": 1195
                        },
                        "uv": 4.0
                    },
                    "astro": {
                        "sunrise": "05:12 AM",
                        "sunset": "06:32 PM",
                        "moonrise": "11:12 PM",
                        "moonset": "08:48 AM",
                        "moon_phase": "Waning Gibbous",
                        "moon_illumination": "60"
                    },
                    "hour": [
                        {
                            "time_epoch": 1668290400,
                            "time": "2022-11-13 00:00",
                            "temp_c": 17.9,
                            "temp_f": 64.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                "code": 1006
                            },
                            "wind_mph": 9.6,
                            "wind_kph": 15.5,
                            "wind_degree": 11,
                            "wind_dir": "NNE",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.97,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 89,
                            "cloud": 72,
                            "feelslike_c": 17.9,
                            "feelslike_f": 64.2,
                            "windchill_c": 17.9,
                            "windchill_f": 64.2,
                            "heatindex_c": 17.9,
                            "heatindex_f": 64.2,
                            "dewpoint_c": 16.1,
                            "dewpoint_f": 61.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.9,
                            "gust_kph": 19.1,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668294000,
                            "time": "2022-11-13 01:00",
                            "temp_c": 17.3,
                            "temp_f": 63.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Light rain shower",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                                "code": 1240
                            },
                            "wind_mph": 6.5,
                            "wind_kph": 10.4,
                            "wind_degree": 14,
                            "wind_dir": "NNE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.95,
                            "precip_mm": 0.2,
                            "precip_in": 0.01,
                            "humidity": 93,
                            "cloud": 100,
                            "feelslike_c": 17.3,
                            "feelslike_f": 63.1,
                            "windchill_c": 17.3,
                            "windchill_f": 63.1,
                            "heatindex_c": 17.3,
                            "heatindex_f": 63.1,
                            "dewpoint_c": 16.2,
                            "dewpoint_f": 61.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 98,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.3,
                            "gust_kph": 13.3,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668297600,
                            "time": "2022-11-13 02:00",
                            "temp_c": 17.3,
                            "temp_f": 63.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 4.3,
                            "wind_kph": 6.8,
                            "wind_degree": 30,
                            "wind_dir": "NNE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 93,
                            "cloud": 51,
                            "feelslike_c": 17.3,
                            "feelslike_f": 63.1,
                            "windchill_c": 17.3,
                            "windchill_f": 63.1,
                            "heatindex_c": 17.3,
                            "heatindex_f": 63.1,
                            "dewpoint_c": 16.1,
                            "dewpoint_f": 61.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 6.0,
                            "gust_kph": 9.7,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668301200,
                            "time": "2022-11-13 03:00",
                            "temp_c": 17.5,
                            "temp_f": 63.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Light rain shower",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                                "code": 1240
                            },
                            "wind_mph": 3.8,
                            "wind_kph": 6.1,
                            "wind_degree": 23,
                            "wind_dir": "NNE",
                            "pressure_mb": 1013.0,
                            "pressure_in": 29.92,
                            "precip_mm": 0.5,
                            "precip_in": 0.02,
                            "humidity": 89,
                            "cloud": 86,
                            "feelslike_c": 17.5,
                            "feelslike_f": 63.5,
                            "windchill_c": 17.5,
                            "windchill_f": 63.5,
                            "heatindex_c": 17.5,
                            "heatindex_f": 63.5,
                            "dewpoint_c": 15.7,
                            "dewpoint_f": 60.3,
                            "will_it_rain": 1,
                            "chance_of_rain": 98,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 5.6,
                            "gust_kph": 9.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668304800,
                            "time": "2022-11-13 04:00",
                            "temp_c": 17.5,
                            "temp_f": 63.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                "code": 1006
                            },
                            "wind_mph": 3.8,
                            "wind_kph": 6.1,
                            "wind_degree": 3,
                            "wind_dir": "N",
                            "pressure_mb": 1013.0,
                            "pressure_in": 29.92,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 89,
                            "cloud": 83,
                            "feelslike_c": 17.5,
                            "feelslike_f": 63.5,
                            "windchill_c": 17.5,
                            "windchill_f": 63.5,
                            "heatindex_c": 17.5,
                            "heatindex_f": 63.5,
                            "dewpoint_c": 15.7,
                            "dewpoint_f": 60.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 5.6,
                            "gust_kph": 9.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668308400,
                            "time": "2022-11-13 05:00",
                            "temp_c": 17.0,
                            "temp_f": 62.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Moderate or heavy rain shower",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/356.png",
                                "code": 1243
                            },
                            "wind_mph": 5.1,
                            "wind_kph": 8.3,
                            "wind_degree": 345,
                            "wind_dir": "NNW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 3.3,
                            "precip_in": 0.13,
                            "humidity": 93,
                            "cloud": 65,
                            "feelslike_c": 17.0,
                            "feelslike_f": 62.6,
                            "windchill_c": 17.0,
                            "windchill_f": 62.6,
                            "heatindex_c": 17.0,
                            "heatindex_f": 62.6,
                            "dewpoint_c": 15.9,
                            "dewpoint_f": 60.6,
                            "will_it_rain": 1,
                            "chance_of_rain": 94,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 7.0,
                            "vis_miles": 4.0,
                            "gust_mph": 7.8,
                            "gust_kph": 12.6,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668312000,
                            "time": "2022-11-13 06:00",
                            "temp_c": 17.3,
                            "temp_f": 63.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 3.1,
                            "wind_kph": 5.0,
                            "wind_degree": 18,
                            "wind_dir": "NNE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.95,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 91,
                            "cloud": 42,
                            "feelslike_c": 17.3,
                            "feelslike_f": 63.1,
                            "windchill_c": 17.3,
                            "windchill_f": 63.1,
                            "heatindex_c": 17.3,
                            "heatindex_f": 63.1,
                            "dewpoint_c": 15.9,
                            "dewpoint_f": 60.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 4.3,
                            "gust_kph": 6.8,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668315600,
                            "time": "2022-11-13 07:00",
                            "temp_c": 17.5,
                            "temp_f": 63.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 3.1,
                            "wind_kph": 5.0,
                            "wind_degree": 18,
                            "wind_dir": "NNE",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.96,
                            "precip_mm": 0.9,
                            "precip_in": 0.04,
                            "humidity": 89,
                            "cloud": 77,
                            "feelslike_c": 17.5,
                            "feelslike_f": 63.5,
                            "windchill_c": 17.5,
                            "windchill_f": 63.5,
                            "heatindex_c": 17.5,
                            "heatindex_f": 63.5,
                            "dewpoint_c": 15.7,
                            "dewpoint_f": 60.3,
                            "will_it_rain": 1,
                            "chance_of_rain": 75,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 4.9,
                            "gust_kph": 7.9,
                            "uv": 4.0
                        },
                        {
                            "time_epoch": 1668319200,
                            "time": "2022-11-13 08:00",
                            "temp_c": 19.1,
                            "temp_f": 66.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 4.9,
                            "wind_kph": 7.9,
                            "wind_degree": 353,
                            "wind_dir": "N",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.97,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 80,
                            "cloud": 57,
                            "feelslike_c": 19.1,
                            "feelslike_f": 66.4,
                            "windchill_c": 19.1,
                            "windchill_f": 66.4,
                            "heatindex_c": 19.1,
                            "heatindex_f": 66.4,
                            "dewpoint_c": 15.5,
                            "dewpoint_f": 59.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 5.6,
                            "gust_kph": 9.0,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668322800,
                            "time": "2022-11-13 09:00",
                            "temp_c": 19.3,
                            "temp_f": 66.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 6.0,
                            "wind_kph": 9.7,
                            "wind_degree": 335,
                            "wind_dir": "NNW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.97,
                            "precip_mm": 1.0,
                            "precip_in": 0.04,
                            "humidity": 79,
                            "cloud": 87,
                            "feelslike_c": 19.3,
                            "feelslike_f": 66.7,
                            "windchill_c": 19.3,
                            "windchill_f": 66.7,
                            "heatindex_c": 19.3,
                            "heatindex_f": 66.7,
                            "dewpoint_c": 15.6,
                            "dewpoint_f": 60.1,
                            "will_it_rain": 1,
                            "chance_of_rain": 95,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 7.8,
                            "gust_kph": 12.6,
                            "uv": 4.0
                        },
                        {
                            "time_epoch": 1668326400,
                            "time": "2022-11-13 10:00",
                            "temp_c": 20.9,
                            "temp_f": 69.6,
                            "is_day": 1,
                            "condition": {
                                "text": "Light rain shower",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                                "code": 1240
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 311,
                            "wind_dir": "NW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.96,
                            "precip_mm": 0.8,
                            "precip_in": 0.03,
                            "humidity": 72,
                            "cloud": 83,
                            "feelslike_c": 20.9,
                            "feelslike_f": 69.6,
                            "windchill_c": 20.9,
                            "windchill_f": 69.6,
                            "heatindex_c": 20.9,
                            "heatindex_f": 69.6,
                            "dewpoint_c": 15.6,
                            "dewpoint_f": 60.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 59,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.3,
                            "gust_kph": 16.6,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668330000,
                            "time": "2022-11-13 11:00",
                            "temp_c": 22.5,
                            "temp_f": 72.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Moderate or heavy rain shower",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/356.png",
                                "code": 1243
                            },
                            "wind_mph": 7.4,
                            "wind_kph": 11.9,
                            "wind_degree": 295,
                            "wind_dir": "WNW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.94,
                            "precip_mm": 3.1,
                            "precip_in": 0.12,
                            "humidity": 63,
                            "cloud": 88,
                            "feelslike_c": 24.7,
                            "feelslike_f": 76.5,
                            "windchill_c": 22.5,
                            "windchill_f": 72.5,
                            "heatindex_c": 24.7,
                            "heatindex_f": 76.5,
                            "dewpoint_c": 15.2,
                            "dewpoint_f": 59.4,
                            "will_it_rain": 1,
                            "chance_of_rain": 97,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 7.0,
                            "vis_miles": 4.0,
                            "gust_mph": 12.1,
                            "gust_kph": 19.4,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668333600,
                            "time": "2022-11-13 12:00",
                            "temp_c": 23.3,
                            "temp_f": 73.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Light rain shower",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                                "code": 1240
                            },
                            "wind_mph": 8.1,
                            "wind_kph": 13.0,
                            "wind_degree": 289,
                            "wind_dir": "WNW",
                            "pressure_mb": 1013.0,
                            "pressure_in": 29.92,
                            "precip_mm": 0.9,
                            "precip_in": 0.04,
                            "humidity": 61,
                            "cloud": 72,
                            "feelslike_c": 25.1,
                            "feelslike_f": 77.2,
                            "windchill_c": 23.3,
                            "windchill_f": 73.9,
                            "heatindex_c": 25.1,
                            "heatindex_f": 77.2,
                            "dewpoint_c": 15.4,
                            "dewpoint_f": 59.7,
                            "will_it_rain": 1,
                            "chance_of_rain": 91,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 14.5,
                            "gust_kph": 23.4,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668337200,
                            "time": "2022-11-13 13:00",
                            "temp_c": 22.7,
                            "temp_f": 72.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 8.5,
                            "wind_kph": 13.7,
                            "wind_degree": 279,
                            "wind_dir": "W",
                            "pressure_mb": 1013.0,
                            "pressure_in": 29.91,
                            "precip_mm": 1.2,
                            "precip_in": 0.05,
                            "humidity": 64,
                            "cloud": 76,
                            "feelslike_c": 24.8,
                            "feelslike_f": 76.6,
                            "windchill_c": 22.7,
                            "windchill_f": 72.9,
                            "heatindex_c": 24.8,
                            "heatindex_f": 76.6,
                            "dewpoint_c": 15.6,
                            "dewpoint_f": 60.1,
                            "will_it_rain": 1,
                            "chance_of_rain": 96,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 16.6,
                            "gust_kph": 26.6,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668340800,
                            "time": "2022-11-13 14:00",
                            "temp_c": 22.4,
                            "temp_f": 72.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Moderate or heavy rain shower",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/356.png",
                                "code": 1243
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 265,
                            "wind_dir": "W",
                            "pressure_mb": 1012.0,
                            "pressure_in": 29.89,
                            "precip_mm": 6.4,
                            "precip_in": 0.25,
                            "humidity": 63,
                            "cloud": 77,
                            "feelslike_c": 24.7,
                            "feelslike_f": 76.5,
                            "windchill_c": 22.4,
                            "windchill_f": 72.3,
                            "heatindex_c": 24.7,
                            "heatindex_f": 76.5,
                            "dewpoint_c": 14.9,
                            "dewpoint_f": 58.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 62,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 7.0,
                            "vis_miles": 4.0,
                            "gust_mph": 13.9,
                            "gust_kph": 22.3,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668344400,
                            "time": "2022-11-13 15:00",
                            "temp_c": 22.6,
                            "temp_f": 72.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 223,
                            "wind_dir": "SW",
                            "pressure_mb": 1012.0,
                            "pressure_in": 29.88,
                            "precip_mm": 0.6,
                            "precip_in": 0.02,
                            "humidity": 60,
                            "cloud": 87,
                            "feelslike_c": 24.8,
                            "feelslike_f": 76.6,
                            "windchill_c": 22.6,
                            "windchill_f": 72.7,
                            "heatindex_c": 24.8,
                            "heatindex_f": 76.6,
                            "dewpoint_c": 14.5,
                            "dewpoint_f": 58.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 68,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 9.6,
                            "gust_kph": 15.5,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668348000,
                            "time": "2022-11-13 16:00",
                            "temp_c": 23.1,
                            "temp_f": 73.6,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 172,
                            "wind_dir": "S",
                            "pressure_mb": 1011.0,
                            "pressure_in": 29.86,
                            "precip_mm": 0.3,
                            "precip_in": 0.01,
                            "humidity": 57,
                            "cloud": 72,
                            "feelslike_c": 24.9,
                            "feelslike_f": 76.8,
                            "windchill_c": 23.1,
                            "windchill_f": 73.6,
                            "heatindex_c": 24.9,
                            "heatindex_f": 76.8,
                            "dewpoint_c": 14.0,
                            "dewpoint_f": 57.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 89,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 8.5,
                            "gust_kph": 13.7,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668351600,
                            "time": "2022-11-13 17:00",
                            "temp_c": 21.6,
                            "temp_f": 70.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 10.3,
                            "wind_kph": 16.6,
                            "wind_degree": 157,
                            "wind_dir": "SSE",
                            "pressure_mb": 1012.0,
                            "pressure_in": 29.87,
                            "precip_mm": 1.5,
                            "precip_in": 0.06,
                            "humidity": 70,
                            "cloud": 77,
                            "feelslike_c": 21.6,
                            "feelslike_f": 70.9,
                            "windchill_c": 21.6,
                            "windchill_f": 70.9,
                            "heatindex_c": 24.5,
                            "heatindex_f": 76.1,
                            "dewpoint_c": 15.9,
                            "dewpoint_f": 60.6,
                            "will_it_rain": 1,
                            "chance_of_rain": 71,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 14.1,
                            "gust_kph": 22.7,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668355200,
                            "time": "2022-11-13 18:00",
                            "temp_c": 19.1,
                            "temp_f": 66.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 4.0,
                            "wind_kph": 6.5,
                            "wind_degree": 164,
                            "wind_dir": "SSE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.5,
                            "precip_in": 0.02,
                            "humidity": 77,
                            "cloud": 73,
                            "feelslike_c": 19.1,
                            "feelslike_f": 66.4,
                            "windchill_c": 19.1,
                            "windchill_f": 66.4,
                            "heatindex_c": 19.1,
                            "heatindex_f": 66.4,
                            "dewpoint_c": 15.1,
                            "dewpoint_f": 59.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 72,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 5.8,
                            "gust_kph": 9.4,
                            "uv": 4.0
                        },
                        {
                            "time_epoch": 1668358800,
                            "time": "2022-11-13 19:00",
                            "temp_c": 19.0,
                            "temp_f": 66.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 10.1,
                            "wind_kph": 16.2,
                            "wind_degree": 118,
                            "wind_dir": "ESE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.95,
                            "precip_mm": 0.9,
                            "precip_in": 0.04,
                            "humidity": 82,
                            "cloud": 70,
                            "feelslike_c": 19.0,
                            "feelslike_f": 66.2,
                            "windchill_c": 19.0,
                            "windchill_f": 66.2,
                            "heatindex_c": 19.0,
                            "heatindex_f": 66.2,
                            "dewpoint_c": 15.8,
                            "dewpoint_f": 60.4,
                            "will_it_rain": 1,
                            "chance_of_rain": 73,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 15.4,
                            "gust_kph": 24.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668362400,
                            "time": "2022-11-13 20:00",
                            "temp_c": 17.2,
                            "temp_f": 63.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Moderate rain at times",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/299.png",
                                "code": 1186
                            },
                            "wind_mph": 5.4,
                            "wind_kph": 8.6,
                            "wind_degree": 103,
                            "wind_dir": "ESE",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.98,
                            "precip_mm": 2.8,
                            "precip_in": 0.11,
                            "humidity": 81,
                            "cloud": 78,
                            "feelslike_c": 17.2,
                            "feelslike_f": 63.0,
                            "windchill_c": 17.2,
                            "windchill_f": 63.0,
                            "heatindex_c": 17.2,
                            "heatindex_f": 63.0,
                            "dewpoint_c": 14.0,
                            "dewpoint_f": 57.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 61,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 8.0,
                            "vis_miles": 4.0,
                            "gust_mph": 9.6,
                            "gust_kph": 15.5,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668366000,
                            "time": "2022-11-13 21:00",
                            "temp_c": 17.4,
                            "temp_f": 63.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 5.6,
                            "wind_kph": 9.0,
                            "wind_degree": 115,
                            "wind_dir": "ESE",
                            "pressure_mb": 1016.0,
                            "pressure_in": 30.01,
                            "precip_mm": 0.1,
                            "precip_in": 0.0,
                            "humidity": 80,
                            "cloud": 87,
                            "feelslike_c": 17.4,
                            "feelslike_f": 63.3,
                            "windchill_c": 17.4,
                            "windchill_f": 63.3,
                            "heatindex_c": 17.4,
                            "heatindex_f": 63.3,
                            "dewpoint_c": 13.8,
                            "dewpoint_f": 56.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 62,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.6,
                            "gust_kph": 15.5,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668369600,
                            "time": "2022-11-13 22:00",
                            "temp_c": 16.6,
                            "temp_f": 61.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.5,
                            "wind_kph": 10.4,
                            "wind_degree": 112,
                            "wind_dir": "ESE",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.03,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 79,
                            "cloud": 6,
                            "feelslike_c": 16.6,
                            "feelslike_f": 61.9,
                            "windchill_c": 16.6,
                            "windchill_f": 61.9,
                            "heatindex_c": 16.6,
                            "heatindex_f": 61.9,
                            "dewpoint_c": 13.0,
                            "dewpoint_f": 55.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.5,
                            "gust_kph": 20.2,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668373200,
                            "time": "2022-11-13 23:00",
                            "temp_c": 16.1,
                            "temp_f": 61.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 5.1,
                            "wind_kph": 8.3,
                            "wind_degree": 89,
                            "wind_dir": "E",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.03,
                            "precip_mm": 0.1,
                            "precip_in": 0.0,
                            "humidity": 79,
                            "cloud": 70,
                            "feelslike_c": 16.1,
                            "feelslike_f": 61.0,
                            "windchill_c": 16.1,
                            "windchill_f": 61.0,
                            "heatindex_c": 16.1,
                            "heatindex_f": 61.0,
                            "dewpoint_c": 12.5,
                            "dewpoint_f": 54.5,
                            "will_it_rain": 1,
                            "chance_of_rain": 72,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.3,
                            "gust_kph": 16.6,
                            "uv": 1.0
                        }
                    ]
                },
                {
                    "date": "2022-11-14",
                    "date_epoch": 1668384000,
                    "day": {
                        "maxtemp_c": 29.7,
                        "maxtemp_f": 85.5,
                        "mintemp_c": 14.3,
                        "mintemp_f": 57.7,
                        "avgtemp_c": 21.0,
                        "avgtemp_f": 69.8,
                        "maxwind_mph": 13.6,
                        "maxwind_kph": 22.0,
                        "totalprecip_mm": 0.5,
                        "totalprecip_in": 0.02,
                        "totalsnow_cm": 0.0,
                        "avgvis_km": 10.0,
                        "avgvis_miles": 6.0,
                        "avghumidity": 57.0,
                        "daily_will_it_rain": 1,
                        "daily_chance_of_rain": 78,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "uv": 5.0
                    },
                    "astro": {
                        "sunrise": "05:12 AM",
                        "sunset": "06:33 PM",
                        "moonrise": "11:55 PM",
                        "moonset": "09:43 AM",
                        "moon_phase": "Waning Gibbous",
                        "moon_illumination": "53"
                    },
                    "hour": [
                        {
                            "time_epoch": 1668376800,
                            "time": "2022-11-14 00:00",
                            "temp_c": 15.6,
                            "temp_f": 60.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 5.4,
                            "wind_kph": 8.6,
                            "wind_degree": 87,
                            "wind_dir": "E",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.04,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 80,
                            "cloud": 5,
                            "feelslike_c": 15.6,
                            "feelslike_f": 60.1,
                            "windchill_c": 15.6,
                            "windchill_f": 60.1,
                            "heatindex_c": 15.6,
                            "heatindex_f": 60.1,
                            "dewpoint_c": 12.2,
                            "dewpoint_f": 54.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.5,
                            "gust_kph": 16.9,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668380400,
                            "time": "2022-11-14 01:00",
                            "temp_c": 15.5,
                            "temp_f": 59.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 5.1,
                            "wind_kph": 8.3,
                            "wind_degree": 104,
                            "wind_dir": "ESE",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.03,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 81,
                            "cloud": 5,
                            "feelslike_c": 15.5,
                            "feelslike_f": 59.9,
                            "windchill_c": 15.5,
                            "windchill_f": 59.9,
                            "heatindex_c": 15.5,
                            "heatindex_f": 59.9,
                            "dewpoint_c": 12.2,
                            "dewpoint_f": 54.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.6,
                            "gust_kph": 15.5,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668384000,
                            "time": "2022-11-14 02:00",
                            "temp_c": 15.2,
                            "temp_f": 59.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 5.1,
                            "wind_kph": 8.3,
                            "wind_degree": 127,
                            "wind_dir": "SE",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.02,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 80,
                            "cloud": 5,
                            "feelslike_c": 15.2,
                            "feelslike_f": 59.4,
                            "windchill_c": 15.2,
                            "windchill_f": 59.4,
                            "heatindex_c": 15.2,
                            "heatindex_f": 59.4,
                            "dewpoint_c": 11.8,
                            "dewpoint_f": 53.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.4,
                            "gust_kph": 15.1,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668387600,
                            "time": "2022-11-14 03:00",
                            "temp_c": 15.1,
                            "temp_f": 59.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 5.4,
                            "wind_kph": 8.6,
                            "wind_degree": 137,
                            "wind_dir": "SE",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.03,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 81,
                            "cloud": 5,
                            "feelslike_c": 15.1,
                            "feelslike_f": 59.2,
                            "windchill_c": 15.1,
                            "windchill_f": 59.2,
                            "heatindex_c": 15.1,
                            "heatindex_f": 59.2,
                            "dewpoint_c": 11.8,
                            "dewpoint_f": 53.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.2,
                            "gust_kph": 14.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668391200,
                            "time": "2022-11-14 04:00",
                            "temp_c": 14.8,
                            "temp_f": 58.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.6,
                            "wind_kph": 12.2,
                            "wind_degree": 134,
                            "wind_dir": "SE",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.04,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 81,
                            "cloud": 6,
                            "feelslike_c": 14.1,
                            "feelslike_f": 57.4,
                            "windchill_c": 14.1,
                            "windchill_f": 57.4,
                            "heatindex_c": 14.8,
                            "heatindex_f": 58.6,
                            "dewpoint_c": 11.6,
                            "dewpoint_f": 52.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.3,
                            "gust_kph": 19.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668394800,
                            "time": "2022-11-14 05:00",
                            "temp_c": 14.3,
                            "temp_f": 57.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 9.8,
                            "wind_kph": 15.8,
                            "wind_degree": 122,
                            "wind_dir": "ESE",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.06,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 84,
                            "cloud": 7,
                            "feelslike_c": 13.1,
                            "feelslike_f": 55.6,
                            "windchill_c": 13.1,
                            "windchill_f": 55.6,
                            "heatindex_c": 14.3,
                            "heatindex_f": 57.7,
                            "dewpoint_c": 11.6,
                            "dewpoint_f": 52.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 15.4,
                            "gust_kph": 24.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668398400,
                            "time": "2022-11-14 06:00",
                            "temp_c": 14.6,
                            "temp_f": 58.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 11.2,
                            "wind_kph": 18.0,
                            "wind_degree": 117,
                            "wind_dir": "ESE",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 83,
                            "cloud": 5,
                            "feelslike_c": 13.3,
                            "feelslike_f": 55.9,
                            "windchill_c": 13.3,
                            "windchill_f": 55.9,
                            "heatindex_c": 14.6,
                            "heatindex_f": 58.3,
                            "dewpoint_c": 11.7,
                            "dewpoint_f": 53.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 16.1,
                            "gust_kph": 25.9,
                            "uv": 4.0
                        },
                        {
                            "time_epoch": 1668402000,
                            "time": "2022-11-14 07:00",
                            "temp_c": 16.7,
                            "temp_f": 62.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 12.8,
                            "wind_kph": 20.5,
                            "wind_degree": 103,
                            "wind_dir": "ESE",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 72,
                            "cloud": 4,
                            "feelslike_c": 16.7,
                            "feelslike_f": 62.1,
                            "windchill_c": 16.7,
                            "windchill_f": 62.1,
                            "heatindex_c": 16.7,
                            "heatindex_f": 62.1,
                            "dewpoint_c": 11.7,
                            "dewpoint_f": 53.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 15.0,
                            "gust_kph": 24.1,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668405600,
                            "time": "2022-11-14 08:00",
                            "temp_c": 19.2,
                            "temp_f": 66.6,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 12.3,
                            "wind_kph": 19.8,
                            "wind_degree": 89,
                            "wind_dir": "E",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 61,
                            "cloud": 7,
                            "feelslike_c": 19.2,
                            "feelslike_f": 66.6,
                            "windchill_c": 19.2,
                            "windchill_f": 66.6,
                            "heatindex_c": 19.2,
                            "heatindex_f": 66.6,
                            "dewpoint_c": 11.4,
                            "dewpoint_f": 52.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 14.1,
                            "gust_kph": 22.7,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1668409200,
                            "time": "2022-11-14 09:00",
                            "temp_c": 21.0,
                            "temp_f": 69.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 12.1,
                            "wind_kph": 19.4,
                            "wind_degree": 81,
                            "wind_dir": "E",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 53,
                            "cloud": 15,
                            "feelslike_c": 21.0,
                            "feelslike_f": 69.8,
                            "windchill_c": 21.0,
                            "windchill_f": 69.8,
                            "heatindex_c": 21.0,
                            "heatindex_f": 69.8,
                            "dewpoint_c": 11.1,
                            "dewpoint_f": 52.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.9,
                            "gust_kph": 22.3,
                            "uv": 6.0
                        },
                        {
                            "time_epoch": 1668412800,
                            "time": "2022-11-14 10:00",
                            "temp_c": 22.4,
                            "temp_f": 72.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 12.5,
                            "wind_kph": 20.2,
                            "wind_degree": 78,
                            "wind_dir": "ENE",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.07,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 47,
                            "cloud": 10,
                            "feelslike_c": 24.4,
                            "feelslike_f": 75.9,
                            "windchill_c": 22.4,
                            "windchill_f": 72.3,
                            "heatindex_c": 24.4,
                            "heatindex_f": 75.9,
                            "dewpoint_c": 10.5,
                            "dewpoint_f": 50.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 14.3,
                            "gust_kph": 23.0,
                            "uv": 6.0
                        },
                        {
                            "time_epoch": 1668416400,
                            "time": "2022-11-14 11:00",
                            "temp_c": 25.1,
                            "temp_f": 77.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 12.1,
                            "wind_kph": 19.4,
                            "wind_degree": 76,
                            "wind_dir": "ENE",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.05,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 42,
                            "cloud": 6,
                            "feelslike_c": 25.5,
                            "feelslike_f": 77.9,
                            "windchill_c": 25.1,
                            "windchill_f": 77.2,
                            "heatindex_c": 25.5,
                            "heatindex_f": 77.9,
                            "dewpoint_c": 11.1,
                            "dewpoint_f": 52.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.9,
                            "gust_kph": 22.3,
                            "uv": 7.0
                        },
                        {
                            "time_epoch": 1668420000,
                            "time": "2022-11-14 12:00",
                            "temp_c": 26.5,
                            "temp_f": 79.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 10.3,
                            "wind_kph": 16.6,
                            "wind_degree": 75,
                            "wind_dir": "ENE",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.03,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 36,
                            "cloud": 22,
                            "feelslike_c": 26.2,
                            "feelslike_f": 79.2,
                            "windchill_c": 26.5,
                            "windchill_f": 79.7,
                            "heatindex_c": 26.2,
                            "heatindex_f": 79.2,
                            "dewpoint_c": 10.2,
                            "dewpoint_f": 50.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.9,
                            "gust_kph": 19.1,
                            "uv": 7.0
                        },
                        {
                            "time_epoch": 1668423600,
                            "time": "2022-11-14 13:00",
                            "temp_c": 29.3,
                            "temp_f": 84.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 8.3,
                            "wind_kph": 13.3,
                            "wind_degree": 77,
                            "wind_dir": "ENE",
                            "pressure_mb": 1016.0,
                            "pressure_in": 30.0,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 31,
                            "cloud": 12,
                            "feelslike_c": 28.3,
                            "feelslike_f": 82.9,
                            "windchill_c": 29.3,
                            "windchill_f": 84.7,
                            "heatindex_c": 28.3,
                            "heatindex_f": 82.9,
                            "dewpoint_c": 10.5,
                            "dewpoint_f": 50.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.6,
                            "gust_kph": 15.5,
                            "uv": 7.0
                        },
                        {
                            "time_epoch": 1668427200,
                            "time": "2022-11-14 14:00",
                            "temp_c": 29.7,
                            "temp_f": 85.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.4,
                            "wind_kph": 11.9,
                            "wind_degree": 79,
                            "wind_dir": "E",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.96,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 28,
                            "cloud": 8,
                            "feelslike_c": 28.4,
                            "feelslike_f": 83.1,
                            "windchill_c": 29.7,
                            "windchill_f": 85.5,
                            "heatindex_c": 28.4,
                            "heatindex_f": 83.1,
                            "dewpoint_c": 9.3,
                            "dewpoint_f": 48.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.5,
                            "gust_kph": 13.7,
                            "uv": 7.0
                        },
                        {
                            "time_epoch": 1668430800,
                            "time": "2022-11-14 15:00",
                            "temp_c": 29.5,
                            "temp_f": 85.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.2,
                            "wind_kph": 11.5,
                            "wind_degree": 76,
                            "wind_dir": "ENE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 27,
                            "cloud": 7,
                            "feelslike_c": 28.0,
                            "feelslike_f": 82.4,
                            "windchill_c": 29.5,
                            "windchill_f": 85.1,
                            "heatindex_c": 28.0,
                            "heatindex_f": 82.4,
                            "dewpoint_c": 8.3,
                            "dewpoint_f": 46.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.3,
                            "gust_kph": 13.3,
                            "uv": 7.0
                        },
                        {
                            "time_epoch": 1668434400,
                            "time": "2022-11-14 16:00",
                            "temp_c": 29.1,
                            "temp_f": 84.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 64,
                            "wind_dir": "ENE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 27,
                            "cloud": 7,
                            "feelslike_c": 27.7,
                            "feelslike_f": 81.9,
                            "windchill_c": 29.1,
                            "windchill_f": 84.4,
                            "heatindex_c": 27.7,
                            "heatindex_f": 81.9,
                            "dewpoint_c": 8.2,
                            "dewpoint_f": 46.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.1,
                            "gust_kph": 13.0,
                            "uv": 7.0
                        },
                        {
                            "time_epoch": 1668438000,
                            "time": "2022-11-14 17:00",
                            "temp_c": 26.8,
                            "temp_f": 80.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 11.2,
                            "wind_kph": 18.0,
                            "wind_degree": 40,
                            "wind_dir": "NE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.94,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 33,
                            "cloud": 9,
                            "feelslike_c": 26.2,
                            "feelslike_f": 79.2,
                            "windchill_c": 26.8,
                            "windchill_f": 80.2,
                            "heatindex_c": 26.2,
                            "heatindex_f": 79.2,
                            "dewpoint_c": 9.3,
                            "dewpoint_f": 48.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.0,
                            "gust_kph": 20.9,
                            "uv": 7.0
                        },
                        {
                            "time_epoch": 1668441600,
                            "time": "2022-11-14 18:00",
                            "temp_c": 23.7,
                            "temp_f": 74.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 13.2,
                            "wind_kph": 21.2,
                            "wind_degree": 38,
                            "wind_dir": "NE",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.98,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 48,
                            "cloud": 14,
                            "feelslike_c": 25.0,
                            "feelslike_f": 77.0,
                            "windchill_c": 23.7,
                            "windchill_f": 74.7,
                            "heatindex_c": 25.0,
                            "heatindex_f": 77.0,
                            "dewpoint_c": 12.1,
                            "dewpoint_f": 53.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 15.2,
                            "gust_kph": 24.5,
                            "uv": 6.0
                        },
                        {
                            "time_epoch": 1668445200,
                            "time": "2022-11-14 19:00",
                            "temp_c": 23.2,
                            "temp_f": 73.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 9.8,
                            "wind_kph": 15.8,
                            "wind_degree": 29,
                            "wind_dir": "NNE",
                            "pressure_mb": 1016.0,
                            "pressure_in": 30.01,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 50,
                            "cloud": 19,
                            "feelslike_c": 24.8,
                            "feelslike_f": 76.6,
                            "windchill_c": 23.2,
                            "windchill_f": 73.8,
                            "heatindex_c": 24.8,
                            "heatindex_f": 76.6,
                            "dewpoint_c": 12.3,
                            "dewpoint_f": 54.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.9,
                            "gust_kph": 19.1,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668448800,
                            "time": "2022-11-14 20:00",
                            "temp_c": 20.9,
                            "temp_f": 69.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 13.2,
                            "wind_kph": 21.2,
                            "wind_degree": 42,
                            "wind_dir": "NE",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.05,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 54,
                            "cloud": 28,
                            "feelslike_c": 20.9,
                            "feelslike_f": 69.6,
                            "windchill_c": 20.9,
                            "windchill_f": 69.6,
                            "heatindex_c": 20.9,
                            "heatindex_f": 69.6,
                            "dewpoint_c": 11.2,
                            "dewpoint_f": 52.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 19.0,
                            "gust_kph": 30.6,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668452400,
                            "time": "2022-11-14 21:00",
                            "temp_c": 19.3,
                            "temp_f": 66.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 11.6,
                            "wind_kph": 18.7,
                            "wind_degree": 44,
                            "wind_dir": "NE",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.2,
                            "precip_in": 0.01,
                            "humidity": 60,
                            "cloud": 88,
                            "feelslike_c": 19.3,
                            "feelslike_f": 66.7,
                            "windchill_c": 19.3,
                            "windchill_f": 66.7,
                            "heatindex_c": 19.3,
                            "heatindex_f": 66.7,
                            "dewpoint_c": 11.3,
                            "dewpoint_f": 52.3,
                            "will_it_rain": 1,
                            "chance_of_rain": 76,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 17.2,
                            "gust_kph": 27.7,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668456000,
                            "time": "2022-11-14 22:00",
                            "temp_c": 19.0,
                            "temp_f": 66.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 13.2,
                            "wind_kph": 21.2,
                            "wind_degree": 48,
                            "wind_dir": "NE",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.11,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 61,
                            "cloud": 45,
                            "feelslike_c": 19.0,
                            "feelslike_f": 66.2,
                            "windchill_c": 19.0,
                            "windchill_f": 66.2,
                            "heatindex_c": 19.0,
                            "heatindex_f": 66.2,
                            "dewpoint_c": 11.2,
                            "dewpoint_f": 52.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 18.8,
                            "gust_kph": 30.2,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1668459600,
                            "time": "2022-11-14 23:00",
                            "temp_c": 17.9,
                            "temp_f": 64.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Light rain shower",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                                "code": 1240
                            },
                            "wind_mph": 13.6,
                            "wind_kph": 22.0,
                            "wind_degree": 40,
                            "wind_dir": "NE",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.11,
                            "precip_mm": 0.3,
                            "precip_in": 0.01,
                            "humidity": 65,
                            "cloud": 56,
                            "feelslike_c": 17.9,
                            "feelslike_f": 64.2,
                            "windchill_c": 17.9,
                            "windchill_f": 64.2,
                            "heatindex_c": 17.9,
                            "heatindex_f": 64.2,
                            "dewpoint_c": 11.2,
                            "dewpoint_f": 52.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 78,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 19.5,
                            "gust_kph": 31.3,
                            "uv": 1.0
                        }
                    ]
                }
            ]
        }
    }
